### ISSUE TITLE
[SPIKE] chore: Research Thoughtworks tech radar on how they render their specfile

### ISSUE THREAD

**Issue by Alex-itu** [NovoNordisk-OpenSource/decentralized-tech-radar#61]

**Comment by zqueamish** [comment]
2 HOURS have been set for this spike.

**Comment by JonasSkjodt** [comment]
This spike has been altered since creation. It will now only focus on inspecting Thoughtworks’ tech radar and its functions to understand how it works. The Thoughtworks tech radar repo can be found here: [Build your own radar](https://github.com/thoughtworks/build-your-own-radar/). Our goal overall is to "hack and extract the whole css, js, html whatever it may be in order to make it work locally".

Take note, if you decide to run their program locally (without docker) you can use webpackets. install webpackets first by using this command from your terminal in the root:

`npm install --save-dev webpack`

Then run the program in root with the following command

`npm run dev`

The generated .html page will then be available at `http://localhost:8080/`. 

—-

Ideas to look at in this spike (since there’s over 40.000 lines of code in their repo)

- general understanding of the entire tech radar set up.
- Webpackets binds the project together with node.js, minifies all js and scss files, and compiles them in one big main.js file, and css file, which is then injected into the html file. We should consider how to get rid of webpackets/node.js while (potentially) still keeping true to how Thoughtworks collects all the js files into one.
- Look at how factory.js works (look in /src/util/factory.js) to understand how the tech radar is built.
- The input field and its button is tied to an operation to build the tech radar, find this function.
- Look for code we could delete in the light weight version (remember this can be re-inserted, we just need it to work in the start)

—

For clarification:
A “lightweight” version of Thoughtwork’s tech radar is set up here: [Light tech radar](https://github.com/JonasSkjodt/thoughtworks-tech-radar-light-version)

The same rules as above apply to run the program, except for re-named quadrant names which follows Novo’s tech radar.

You can test the radar with the [following csv](
https://raw.githubusercontent.com/August-Brandt/DTR-specfile-generator/main/specfile.csv) from August.

This light version repo will be used temporarily to reengineer Thoughtwork’s tech radar into the Novo tech radar project. The light version repo will delete as much unused code as we can to make our current goLang program work with the tech radar.

Once it does, we could engineer some of the deleted Thoughtworks code back in, trying our best to be faithful to Thoughtworks original code. This will make future Thoughtworks tech radar updates easier to implement for Novo.

**Comment by JonasSkjodt** [comment]
> 2 HOURS have been set for this spike.
> 
> * Remember to research the free libraries.

I'd suggest 4 hours.
